#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=slicm

#
# Build a loadable module
#
LOADABLE_MODULE=1

#
# Build use c++11 standard
#
CPPFLAGS += -std=c++11

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
