#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
# DIRS
#      A space separated list of subdirectories that should be built. They will be built, one at a time, in the order specified.
# PARALLEL_DIRS
#      A list of directories that can be built in parallel. These will be built after the directories in DIRS have been built.
PARALLEL_DIRS=slicm

include $(LEVEL)/Makefile.common
