#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=Slicm

#
# List libraries that we'll need
# We use LIBS because sample is a dynamic library.
#
#USEDLIBS = slicm

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

